stages:
- doc
- cleanup

before_script:
- vagga _init_storage_dir --allow-multiple bigl-uikit

doc:
  stage: doc
  script:
  - vagga build
  - gitlab-publish doc_dist bigl-uikit

cleanup:
  stage: cleanup
  script:
  - vagga _clean --unused --at-least 1day
