stages:
- build

before_script:
- vagga --version

uikit-css:
  stage: build
  script:
  - vagga compile-uikit-css

doc-css:
  stage: build
  script:
  - vagga compile-doc-css

doc-html:
  stage: build
  script:
  - vagga compile-doc-html

collect-static:
  stage: build
  script:
  - vagga collect-static

publish:
  stage: build
  script:
  - gitlab-publish doc_dist bigl-uikit
